name: Deploy-S3

on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18 ]
    
    steps:
        - name: checkout Github Action
          uses: actions/checkout@v4
          with:
            node-version: ${{ matrix.node-version }}

        - name: rename vue
          run: git mv ${{ github.workspace }}/src/components/Home ${{ github.workspace }}/src/components/home

        - name: NPM Install
          run: npm install

        - name: Build
          run: npm run build

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ap-northeast-2
      

        - name: Deploy
          uses: lbertenasco/s3-deploy@v1
          with:
            folder: dist
            bucket: ${{ secrets.BUCKET_NAME }}
            dist-id: ${{ secrets.DISTRIBUTION_ID }}
            invalidation: / *

