name: Deploy-S3

on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: 'ap-northeast-2'

    strategy:
      matrix:
        node-version: [ 18 ]
    
    steps:
        - name: checkout Github Action
          uses: actions/checkout@v4
          with:
            node-version: ${{ matrix.node-version }}

        - name: List src/views directory
          run: ls -l ${{ github.workspace }}/src/views

        - name: rename vue
          run: git mv /src/components/Home /src/components/home

        - name: NPM Install
          run: npm install

        - name: Build
          run: npm run build

        - name: Deploy
          uses: lbertenasco/s3-deploy@v1
          with:
            folder: dist
            bucket: ${{ secrets.BUCKET_NAME }}
            dist-id: ${{ secrets.DISTRIBUTION_ID }}
            invalidation: / *

